import Head from "next/head";
import Customers from "../components/customers/customers";
import RenderCatigory from "../components/renderCategories/renderCategories";
import Deliveries from "../components/deliveries/deliveries";
import Nearbies from "../components/nearbies/nearbies";
import Header from "../components/header/header";
import Footer from "../components/footer/footer";
import { useState } from "react";

export default function Home() {
  const [language, setLanguage] = useState([]);

  return (
    <>
      <Head>
        <title>INTEX - INTEX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/intex.svg" />
      </Head>
      <Header lan={language} setLan={setLanguage} />
      <RenderCatigory lan={language} />
      <Deliveries lan={language} />
      <Customers lan={language} />
      <Nearbies lan={language} />
      <Footer lan={language} />
    </>
  );
}
